### ISSUE TITLE
Problem to install

### ISSUE THREAD

**Issue by jmd87fr** [EduardoKrausME/moodle-local_geniai#1]
Hi Edouardo, 
I tried to install your plugin on my Moodle 4.3.3+ (Build: 20240301).
I downloaded the .zip here.
here's what I got. 
Impossible to uninstall, I had to rename the folder directly on the server.   
![image](https://github.com/EduardoKrausME/moodle-local_geniai/assets/5038301/b7a29e20-da49-493a-b8ae-b173fdc53bef)

**Comment by eduardokraus** [comment]
Try again https://github.com/EduardoKrausME/moodle-local_geniai/commit/6686b717347ceae7b329af65781a54eb0863a45d

**Comment by jmd87fr** [comment]
HI Eduardo
Thank you for your efforts 
Unfortunately I get this result with .zip last version

**
Débogage de l’output activé
ZIP /home/jmd87fr/moodledata/temp/tool_installaddon/65f6c203f0fc7/plugin.zip
Validation de local_geniai ... OK
  [OK] Nom du plugin à installer [geniai] 

 
  [OK] Version du plugin [2024031600] 
  [OK] Version de Moodle requise [2011120500] 
  [OK] Nom complet du composant [local_geniai] 
  [OK] Niveau de maturité déclaré [MATURITY_STABLE] 

 
  [OK] Détails de la version du plugin [1.0.10] 
  [Débogage] Fichier de langue trouvé [local_geniai] 
  [OK] Vérification des droits d’accès en écriture [/home/jmd87fr/public_html/fael/local] 

Validation effectuée. L’installation peut continuer**

Exception : Class "local_geniai\events\event_observers" not found
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 36 of /local/geniai/lib.php: Error thrown
    line 1506 of /lib/outputrenderers.php: call to local_geniai_before_footer()
    line 547 of /lib/outputrenderers.php: call to core_renderer->footer()
    line 181 of /admin/renderer.php: call to plugin_renderer_base->__call()
    line 574 of /admin/index.php: call to core_admin_renderer->upgrade_environment_page()

Exception : Class "local_geniai\events\event_observers" not found
Debug info:
Error code: generalexceptionmessage
Stack trace:

    line 36 of /local/geniai/lib.php: Error thrown
    line 1506 of /lib/outputrenderers.php: call to local_geniai_before_footer()
    line 3062 of /lib/outputrenderers.php: call to core_renderer->footer()
    line 390 of /lib/setuplib.php: call to core_renderer->fatal_error()
    line ? of unknownfile: call to default_exception_handler()

**Comment by jmd87fr** [comment]
Edit : Googd News. 
I start again 
I hadn't uninstalled the old version (just renamed it on the server). Once the uninstall procedure had been completed. The plugin installed normally. 
When I put my API key => Bug :-(  
- graphic theme is broken. 
- I have this msg (see screenshot) 
![image](https://github.com/EduardoKrausME/moodle-local_geniai/assets/5038301/9dcacf04-e6a6-42cc-aabf-2612b1569e0b)

Regards [From Limoges ](https://fr.wikipedia.org/wiki/Limoges)
