### ISSUE TITLE
Namespace collisions

### ISSUE THREAD

**Issue by volodymyrdovhan** [EduardoKrausME/moodle-local_geniai#10]
Hello,

According to Moodle standards, all custom classes that are not part of the core API should be placed in the 'classes/local' folder to avoid potential namespace collisions. You can refer to the guidelines here:
[Namespace Collisions - Moodle Plugin Checklist](https://moodledev.io/general/community/plugincontribution/checklist#namespace-collisions)
[Level 2 Namespaces](https://moodledev.io/general/development/policies/codingstyle#rules-for-level2)

Could you please move folders `classes/util`, `classes/report` and `classes/markdown` to the `classes/local` folder?

**Comment by eduardokraus** [comment]
I thought it was only for MOD because of the non-existence of the "mod_" prefix
