### ISSUE TITLE
Missed Privacy implementation for external API

### ISSUE THREAD

**Issue by volodymyrdovhan** [EduardoKrausME/moodle-local_geniai#8]
Hello,
Missed Privacy implementation for external API:
https://moodledev.io/docs/4.5/apis/subsystems/privacy#indicating-that-you-export-data-to-an-external-location

More details:
[Privacy API Checklist](https://moodledev.io/general/community/plugincontribution/checklist#privacy)
[Moodle Privacy API Documentation](https://moodledev.io/docs/4.5/apis/subsystems/privacy)

**Comment by eduardokraus** [comment]
This morning, before you opened this issue, I was already reflecting on the topic and reviewing the same documentation you mentioned.

It is important to highlight that no data is sent to OpenAI, except for the course name and the Moodle name.

Although the student's name is displayed, it does not come from OpenAI; it is just static text.

**Comment by volodymyrdovhan** [comment]
@eduardokraus Based on our internal discussions, if your plugin does not transmit any personal data to an external service, implementing a null provider with the Privacy API is sufficient, which you have already done.
Therefore, I'm closing this issue.
